# ref: https://docs.travis-ci.com/user/languages/python
language: python

# Python versions to build
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command(s) to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

# build command(s)
script:
  - nosetests --verbose --with-coverage --cover-branches --cover-package=tvdb_api_v2

# after success command(s)
after_success:
  - coveralls
