# ref: https://docs.travis-ci.com/user/languages/python
language: python

# Build matrix
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial # Required for Python >= 3.7
      sudo: true # Required for Python >= 3.7
  fast_finish: true # Finish build immediately once one of the jobs fails.

# command(s) to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

# build command(s)
script:
  - nosetests --verbose --with-coverage --cover-branches --cover-package=tvdb_api

# after success command(s)
after_success:
  - coveralls
