# ref: https://docs.travis-ci.com/user/languages/python
language: python

# Python versions to build
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  #- "3.5-dev" # 3.5 development branch
  #- "nightly" # points to the latest development branch e.g. 3.6-dev

# command(s) to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

# build command(s)
script:
  - nosetests --with-coverage --cover-package=tvdb_api_v2 --cover-branches

# after success command(s)
after_succes:
  - coveralls
